#For Windows Server 2012 
#Made a quick script for adding ransomware extensions and know files to the file screen file groups. This is so you can easily keep multiple file servers with FSRM in sync and make updates in one file pushed out to multiple servers.

#Use the New-FSRMFileGroup cmdlet for new file groups 
#https://technet.microsoft.com/en-us/library/jj900600(v=wps.630).aspx

#UseSet-FSRMFileGroup for updating existing file groups 
#https://technet.microsoft.com/en-us/library/jj900615(v=wps.630).aspx

Set-FsrmFileGroup -Name "<Enter File Group Name here>" -IncludePattern @("*!recover!*.*", "*+recover+*.*", "*-recover-*.*", "*.0x0", "*.1999", "*.73i87A", "*.AES256", "*.CTB2", "*.CrySiS", "*.CryptoTorLocker2015!", "*.EnCiPhErEd", "*.Encrypted", "*.KEYHOLES", "*.KEYZ", "*.LOL!", "*.LeChiffre", "*.OMG!", "*.PoAr2w", "*.R4A", "*.R5A", "*.RADAMANT", "*.RDM", "*.RRK", "*.SUPERCRYPT", "*.XRNT", "*.aaa", "*.abc", "*.better_call_saul", "*.bleep", "*.bloc", "*.btc", "*.btc-help-you", "*.btcbtcbtc", "*.cbf", "*.cerber", "*.chifrator@qq_com", "*.clf", "*.code", "*.coverton", "*.crime", "*.crinf", "*.crjoker", "*.cry", "*.crypt", "*.crypted", "*.crypto", "*.cryptotorlocker*", "*.ctbl", "*.czvxce", "*.darkness", "*.dyatel@qq_com", "*.ecc", "*.enc", "*.encedRSA", "*.encrypt", "*.encryptedAES", "*.encryptedRSA", "*.encryptedped", "*.enigma", "*.exx", "*.ezz", "*.frtrss", "*.fucked", "*.fun", "*.good", "*.gruzin@qq_com", "*.gws", "*.ha3", "*.hb15", "*.helpdecrypt@ukr_net", "*.hydracrypt_ID*", "*.infected", "*.justbtcwillhelpyou", "*.keybtc@inbox_com", "*.kimcilware", "*.kkk", "*.korrektor", "*.kraken", "*.lock", "*.lock*", "*.locked", "*.locky", "*.magic", "*.micro", "*.nalog@qq_com", "*.nochance",  "*.one-we_can-help_you", "*.oor", "*.oplata@qq_com", "*.oshit", "*.p5tkjw", "*.pizda@qq_com", "*.relock@qq_com", "*.remind", "*.rokku", "*.ryp", "*.sanction", "*.scl", "*.sport", "*.surprise", "*.toxcrypt", "*.troyancoder@qq_com", "*.trun", "*.ttt", "*.vault", "*.vscrypt", "*.vvv", "*.xort", "*.xrtn", "*.xtbl", "*.xxx", "*.xyz", "*.zzz", "*.{CRYPTENDBLACKDC}", "*DECRYPT_INSTRUCTION*", "*_Locky_recover_instructions*", "*_crypt*", "*_help_instruct*.*", "*_recover_*.*", "*_secret_code*", "*decrypt my file*.*", "*decryptmyfiles*.*", "*files_are_encrypted.*", "*gmail*.crypt", "*rec0ver*.*", "*recover_instruction*.*", "*recover}-*.*", "*restore_fi*.*", "*want your files back.*", "*warning-!!*.*", "Coin.Locker.txt", "DECRYPT_ReadMe*", "DecryptAllFiles*", "YOUR_FILES.HTML", "_help_instruct*.*", "_how_recover*", "confirmation.key", "cryptolocker.*", "de_crypt_readme.*", "decrypt-instruct*.*", "decrypt_instruct*.*", "enc_files*", "enc_files.txt", "encryptor_raas_readme_liesmich*", "help_decrypt*.*", "help_decrypt_your_files*", "help_file_*.*", "help_instructions.*", "help_recover*.*", "help_restore*.*", "help_your_file*.*", "how to decrypt*.*", "how_recover*.*", "how_to_decrypt*.*", "how_to_recover*.*", "howto_restore*.*", "howtodecrypt*.*", "install_tor*.*", "last_chance.txt", "message.txt", "readme_decrypt*.*", "readme_for_decrypt*.*", "recovery+*.*", "recovery_file.txt", "recovery_key.txt", "vault.hta", "vault.key", "vault.txt", "your_files.url")
